version: '3'
services:

  diabetes-mysql:
    image: mysql:5.7
    container_name: diabetes_db
    ports: 
      - 3306:3306
    environment: 
      - MYSQL_DATABASE=root
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - db:/var/lib/mysql
      
volumes:
  db:
    driver: local